---
# Main PlayBook

- name: Configuration for Debian
  sudo: yes
  remote_user: root
  hosts: debian
  roles:
    - ssh
    - firewall
  vars:
    - firewall_ssh_port: 2222

- name: Configuration for RedHat
  sudo: yes
  remote_user: root
  hosts: redhat
  roles:
    - ssh
    - firewall
  vars:
    - firewall_ssh_port: 2222

