---
# Main PlayBook

- name: Configuration for Debian
  sudo: yes
  remote_user: root
  hosts: debian
  roles:
    - ssh
    - firewall

- name: Configuration for RedHat
  sudo: yes
  remote_user: root
  hosts: redhat
  roles:
    - ssh
    - firewall

- name: Configuration for CentOS
  sudo: yes
  remote_user: root
  hosts: centos
  roles:
    - ssh
    - firewall
