---
# Main PlayBook

- name: Configuration for Debian
  sudo: yes
  remote_user: root
  roles:
    - ssh

- name: Configuration for RedHat
  sudo: yes
  remote_user: root
  roles:
    - ssh

- name: Configuration for CentOS
  sudo: yes
  remote_user: root
  roles:
    - ssh
