---
# Main PlayBook

- name: Configuration for Debian
  sudo: yes
  remote_user: root
  hosts: debian
  roles:
    - common
    - ssh
    - firewall
    - fail2ban
    - network
    - audit-logs
  vars:
    - firewall_ssh_port: 2222

- name: Configuration for RedHat
  sudo: yes
  remote_user: root
  hosts: redhat
  roles:
    - common
    - ssh
    - firewall
    - fail2ban
    - network
    - audit-logs
  vars:
    - firewall_ssh_port: 2222

