---
- name: add pubkey to authorized_keys on host
  authorized_key: user=root
    key="{{ lookup('file', '../../../adrien.pub') }}"
  register: add_identity_key
  when: ssh_identity_key is defined

- name: Disable empty passwd login
  lineinfile: dest={{ sshd_config }} regexp="^#?PermitEmptyPasswords" line="PermitEmptyPasswords no"
  notify: restart sshd

- name: Disable remote root login
  lineinfile: dest={{ sshd_config }} regexp="^#?PermitRootLogin" line="PermitRootLogin no"
  notify: restart sshd

- name: Disable passwd login
  lineinfile: dest={{ sshd_config }} regexp="^#?PasswordAuthentication" line="PasswordAuthentication no"
  when: add_identity_key|success and not add_identity_key|skipped
  notify: restart sshd

- name: Enable PAM auth
  lineinfile: dest={{ sshd_config }} regexp="^#?UsePAM" line="UsePAM yes"
  notify: restart sshd
