---

  - name: disable - IP Forwarding
    sysctl: name=net.ipv4.ip_forward value=0 state=present

  - name: disable - send packet redirects
    sysctl: name=net.ipv4.conf.all.send_redirects value=0 state=present

  - name: log - suspicious packets
    sysctl: name=net.ipv4.conf.all.log_martians value=1 state=present

  - name: enable - ignore broadcast requests
    sysctl: name=net.ipv4.icmp_echo_ignore_broadcasts value=1 state=present

  - name: enable - TCP SYN Cookies
    sysctl: name=net.ipv4.tcp_syncookies value=1  state=present

  - name: disable - IPv6
    sysctl: name=net.ipv6.conf.all.disable_ipv6 value=1 state=present