
---
- name: is iptables installed on RedHat ?
  yum: pkg=iptables state=installed
  when: ansible_os_family == 'RedHat'

- name: is iptables installed on Debian ?
  apt: pkg=iptables state=installed
  when: ansible_os_family == 'Debian'

- name: Flush iptables the first time playbook runs.
  command: iptables -F creates=/etc/init.d/firewall

- name: Copy firewall script in final place
  template: src=firewall.bash.j2 dest=/etc/firewall.bash owner=root group=root mode=0744
  notify: restart firewall

- name: Copy firewall init script in final place
  template: src=firewall.j2 dest=/etc/init.d/firewall owner=root group=root mode=0755

- name: Ensure the firewall is enabled and will start on boot.
  service: name=firewall state=started enabled=yes